name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
      
          - name: Set tag name
            id: tag_name
            run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT  
            
          - name: Extract branch name
            id: branch_name
            run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
            
          #- name: 'Build Inventory Image'
          #  run: |
          #    docker build . --tag ghcr.io/nicolas-fer/${{ github.event.repository.name }}:${{ steps.branch_name.outputs.branch }}-${{ steps.tag_name.outputs.sha_short }} -f ./src/Gamee/Dockerfile
          #    docker push ghcr.io/nicolas-fer/${{ github.event.repository.name }}:${{ steps.branch_name.outputs.branch }}-${{ steps.tag_name.outputs.sha_short }}
          
          - name: Prune
            uses: vlaurin/action-ghcr-prune@v0.5.0
            with:
              token: ${{ secrets.PRUNE_KEY }}
              container: ${{ github.event.repository.name }}
              dry-run: true # Dry-run first, then change to `false`
              keep-last: 2
              prune-tags-regexes: |
                ^.{7,}$
