name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
              
          - name: Set tag name
            id: vars
            run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT  
            
          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/nfsadevelop/store:${{ steps.vars.outputs.sha_short }} -f ./Dockerfile
              docker push ghcr.io/nfsadevelop/store:${{ steps.vars.outputs.sha_short }}
