name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: /src/Gamee/Dockerfile
        tags: user/app:latest
